"""BT90 bootstrap helpers.

Die JS-Dateien im Repo bleiben authoritative.
Dieses Paket haelt nur die fuer BT90 eingefrorenen Referenzlisten bereit.
"""

from .authority_snapshot import (
    ALLOWED_PPO_BUILD_LOCATIONS,
    JS_AUTHORITATIVE_ARTIFACTS,
    JS_AUTHORITY_FILES,
    OPTIONAL_PROJECTED_FIELDS,
    READ_ONLY_RUNTIME_SURFACES,
    TRAINER_TRANSITION_INFO_FIELDS,
    TRAINER_TRANSITION_TOP_LEVEL_FIELDS,
    TRAINING_V1_INFO_FIELDS,
    TRAINING_V1_REQUIRED_FIELDS,
)

__all__ = [
    "ALLOWED_PPO_BUILD_LOCATIONS",
    "JS_AUTHORITATIVE_ARTIFACTS",
    "JS_AUTHORITY_FILES",
    "OPTIONAL_PROJECTED_FIELDS",
    "READ_ONLY_RUNTIME_SURFACES",
    "TRAINER_TRANSITION_INFO_FIELDS",
    "TRAINER_TRANSITION_TOP_LEVEL_FIELDS",
    "TRAINING_V1_INFO_FIELDS",
    "TRAINING_V1_REQUIRED_FIELDS",
]
