export const HUNT_CONFIG = Object.freeze({
    DEFAULT_MODE: 'HUNT',
    DEFAULT_RESPAWN_ENABLED: true,
    PLAYER_MAX_HP: 100,
    PLAYER_REGEN_PER_SECOND: 2.0,
    PLAYER_REGEN_DELAY: 3.0,
    SHIELD_MAX_HP: 40,
    COLLISION_DAMAGE: Object.freeze({
        WALL: 20,
        TRAIL: 28,
        PLAYER_CRASH: 40,
    }),
    MG: Object.freeze({
        DAMAGE: 7.75,
        COOLDOWN: 0.08,
        OVERHEAT_PER_SHOT: 9,
        COOLING_PER_SECOND: 20,
        LOCKOUT_THRESHOLD: 96,
        LOCKOUT_SECONDS: 0.75,
        RANGE: 95,
        MIN_FALLOFF: 0.5,
        AIM_DOT_MIN: 0.965,
        TRAIL_SAMPLE_STEP: 0.45,
        TRAIL_HIT_RADIUS: 0.78,
        TRAIL_SELF_SKIP_RECENT: 8,
        TRACER_BEAM_RADIUS: 0.16,
        TRACER_BULLET_RADIUS: 0.42,
    }),
    TARGETING: Object.freeze({
        MUZZLE_OFFSET: 2.1,
        PROJECTILE_SPAWN_OFFSET: 2.2,
        TRAIL_DESCRIPTOR_MAX_DRIFT: 1.25,
        TRAIL_PROBE_MIN_STEP: 0.01,
        TRAIL_LINE_MIN_SAMPLE_STEP: 0.2,
        TRAIL_HIT_RADIUS_MIN: 0.12,
        TRAIL_DENSE_SCAN_STEP_SCALE: 0.5,
        TRAIL_DENSE_SCAN_MIN_STEP: 0.12,
        PLAYER_HITBOX_MIN_RADIUS: 0.2,
        GEOMETRY_EPSILON: 0.000001,
        OPTIMIZED_SCAN_ENABLED: true,
        OPTIMIZED_SCAN_STEP_MULTIPLIER: 2.0,
        OPTIMIZED_SCAN_MAX_STEP: 1.1,
    }),
    ROCKET: Object.freeze({
        VISUAL_SCALE_WEAK: 1.7,
        VISUAL_SCALE_MEDIUM: 1.95,
        VISUAL_SCALE_HEAVY: 2.2,
        VISUAL_SCALE_MEGA: 2.6,
        COLLISION_RADIUS_MULTIPLIER: 1.65,
        HOMING_TURN_RATE: 6.2,
        HOMING_MIN_TURN_RATE: 0.1,
        HOMING_LOCK_ON_ANGLE: 32,
        HOMING_MIN_LOCK_ON_ANGLE: 5,
        HOMING_REACQUIRE_INTERVAL: 0.12,
        HOMING_MIN_REACQUIRE_INTERVAL: 0.04,
        HOMING_FALLBACK_REACQUIRE_INTERVAL: 0.2,
        HOMING_RANGE: 130,
        HOMING_MIN_RANGE: 10,
        HOMING_SPEED_EPSILON: 0.0001,
        PORTAL_EXIT_FORWARD_OFFSET: 1.5,
        FOAM_BOUNCE_MAX_COUNT: 3,
        FOAM_BOUNCE_NORMAL_BIAS: 0.08,
        FOAM_BOUNCE_SPEED_MULTIPLIER: 1.02,
        FOAM_BOUNCE_POSITION_MIN_OFFSET: 0.2,
        FOAM_BOUNCE_POSITION_RADIUS_SCALE: 1.25,
        FOAM_BOUNCE_COOLDOWN: 0.045,
        FOAM_BOUNCE_TTL_PENALTY: 0.02,
        FLAME_FLICKER_BASE: 0.7,
        FLAME_FLICKER_AMPLITUDE: 0.3,
        FLAME_FLICKER_SPEED: 30,
        FLAME_FLICKER_INDEX_PHASE: 7,
        EXPLOSION_RADIUS: 25,
        EXPLOSION_DAMAGE_FALLOFF: 0.5,
        TRAIL_OVERFLOW_DAMAGE_PER_METER: 2.5,
    }),
    FEEDBACK: Object.freeze({
        MG_IMPACT: Object.freeze({
            count: 16,
            speed: 8.5,
            size: 0.38,
            life: 0.24,
            gravity: -4.0,
            color: 0xffb347,
        }),
        TRAIL_IMPACT: Object.freeze({
            count: 20,
            speed: 7.6,
            size: 0.44,
            life: 0.32,
            gravity: -4.8,
            color: 0x33a8ff,
            destroyedColor: 0x66ddff,
        }),
        SHIELD_IMPACT: Object.freeze({
            count: 22,
            speed: 6.6,
            size: 0.52,
            life: 0.4,
            gravity: -1.2,
            color: 0x66d9ff,
            breakColor: 0xb8f6ff,
        }),
        ROCKET_IMPACT: Object.freeze({
            count: 42,
            speed: 13.5,
            size: 0.92,
            life: 0.68,
            gravity: -6.4,
            weakColor: 0xffcc66,
            mediumColor: 0xff8844,
            heavyColor: 0xff3344,
            megaColor: 0xcc11ff,
        }),
        TRAIL_EXPLOSION: Object.freeze({
            countPerSegment: 8,
            speed: 10.0,
            size: 0.6,
            life: 0.45,
            gravity: -5.0,
            color: 0x44ccff,
        }),
    }),
    ROCKET_TIERS: Object.freeze({
        WEAK: Object.freeze({ damage: 10, spawnChance: 0.5, trailBlastMeters: 2 }),
        MEDIUM: Object.freeze({ damage: 20, spawnChance: 0.28, trailBlastMeters: 4 }),
        HEAVY: Object.freeze({ damage: 40, spawnChance: 0.18, trailBlastMeters: 10 }),
        MEGA: Object.freeze({ damage: 70, spawnChance: 0.03, trailBlastMeters: 30 }),
    }),
    ROCKET_PICKUP_SPAWN_CHANCE: 0.28,
    PICKUP_WEIGHTS: Object.freeze({
        SHIELD: 1.45,
        SPEED_UP: 1.0,
        GHOST: 0.75,
        THICK: 0.55,
        THIN: 0.4,
        SLOW_TIME: 0.35,
        SLOW_DOWN: 0,
        INVERT: 0,
    }),
    TRAIL_SEGMENT_HP: 3,
    RESPAWN: Object.freeze({
        DELAY_SECONDS: 3.0,
        INVULNERABILITY_SECONDS: 1.25,
        MIN_ENEMY_DISTANCE: 18,
        RESET_INVENTORY: true,
        START_LOADOUT: Object.freeze(['ROCKET_WEAK']),
        RECOVERY_SHIELD_HP: 18,
    }),
});
