export const HUNT_CONFIG = Object.freeze({
    DEFAULT_MODE: 'CLASSIC',
    DEFAULT_RESPAWN_ENABLED: false,
    PLAYER_MAX_HP: 100,
    PLAYER_REGEN_PER_SECOND: 2.0,
    PLAYER_REGEN_DELAY: 3.0,
    SHIELD_MAX_HP: 40,
    COLLISION_DAMAGE: Object.freeze({
        WALL: 20,
        TRAIL: 28,
        PLAYER_CRASH: 40,
    }),
    MG: Object.freeze({
        DAMAGE: 8,
        COOLDOWN: 0.08,
        OVERHEAT_PER_SHOT: 7,
        COOLING_PER_SECOND: 24,
        LOCKOUT_THRESHOLD: 100,
        LOCKOUT_SECONDS: 1.2,
        RANGE: 95,
        MIN_FALLOFF: 0.5,
        AIM_DOT_MIN: 0.965,
        TRAIL_SAMPLE_STEP: 0.45,
        TRAIL_HIT_RADIUS: 0.78,
        TRAIL_SELF_SKIP_RECENT: 8,
        TRACER_BEAM_RADIUS: 0.16,
        TRACER_BULLET_RADIUS: 0.42,
    }),
    ROCKET: Object.freeze({
        VISUAL_SCALE_WEAK: 1.7,
        VISUAL_SCALE_MEDIUM: 1.95,
        VISUAL_SCALE_STRONG: 2.2,
        COLLISION_RADIUS_MULTIPLIER: 1.65,
        HOMING_TURN_RATE: 6.2,
        HOMING_LOCK_ON_ANGLE: 32,
        HOMING_REACQUIRE_INTERVAL: 0.12,
        HOMING_RANGE: 130,
    }),
    FEEDBACK: Object.freeze({
        MG_IMPACT: Object.freeze({
            count: 16,
            speed: 8.5,
            size: 0.38,
            life: 0.24,
            gravity: -4.0,
            color: 0xffb347,
        }),
        TRAIL_IMPACT: Object.freeze({
            count: 20,
            speed: 7.6,
            size: 0.44,
            life: 0.32,
            gravity: -4.8,
            color: 0x33a8ff,
            destroyedColor: 0x66ddff,
        }),
        SHIELD_IMPACT: Object.freeze({
            count: 22,
            speed: 6.6,
            size: 0.52,
            life: 0.4,
            gravity: -1.2,
            color: 0x66d9ff,
            breakColor: 0xb8f6ff,
        }),
        ROCKET_IMPACT: Object.freeze({
            count: 42,
            speed: 13.5,
            size: 0.92,
            life: 0.68,
            gravity: -6.4,
            weakColor: 0xffcc66,
            mediumColor: 0xff8844,
            strongColor: 0xff3344,
        }),
    }),
    ROCKET_TIERS: Object.freeze({
        WEAK: Object.freeze({ damage: 15, spawnChance: 0.6 }),
        MEDIUM: Object.freeze({ damage: 35, spawnChance: 0.3 }),
        STRONG: Object.freeze({ damage: 60, spawnChance: 0.1 }),
    }),
    ROCKET_PICKUP_SPAWN_CHANCE: 0.4,
    TRAIL_SEGMENT_HP: 3,
    RESPAWN: Object.freeze({
        DELAY_SECONDS: 3.0,
        INVULNERABILITY_SECONDS: 1.0,
    }),
});
