export const PARCOURS_MAPS = Object.freeze({
    parcours_rift: {
        name: 'Parcours Rift',
        size: [260, 84, 180],
        obstacles: [
            { pos: [-98, 20, 0], size: [12, 40, 72], kind: 'foam' },
            { pos: [-70, 20, -42], size: [34, 40, 8] },
            { pos: [-58, 20, 40], size: [30, 40, 8], kind: 'foam' },
            { pos: [-24, 24, -18], size: [28, 46, 12], tunnel: { radius: 4.8, axis: 'x' } },
            { pos: [12, 32, 14], size: [26, 54, 10], kind: 'foam', tunnel: { radius: 4.2, axis: 'x' } },
            { pos: [40, 38, 0], size: [12, 62, 72] },
            { pos: [70, 32, -24], size: [28, 52, 10], tunnel: { radius: 4.5, axis: 'x' } },
            { pos: [88, 28, 0], size: [8, 30, 70], kind: 'foam' },
            { shape: 'tube', kind: 'hard', start: [-38, 20, -54], end: [6, 30, -54], radius: 4.4 },
            { shape: 'tube', kind: 'hard', start: [20, 38, 44], end: [74, 30, 44], radius: 4.1 },
        ],
        portals: [
            { a: [-14, 30, -70], b: [30, 40, 66], color: 0x00ffcc },
            { a: [42, 38, -60], b: [86, 28, 58], color: 0xff88cc },
        ],
        gates: [
            {
                id: 'rift_boost_entry',
                type: 'boost',
                pos: [-66, 18, 0],
                forward: [1, 0, 0],
                params: { duration: 1.4, forwardImpulse: 44, bonusSpeed: 52, cooldown: 1.0 },
            },
            {
                id: 'rift_slingshot_helix',
                type: 'slingshot',
                pos: [18, 34, 0],
                forward: [1, 0, 0],
                up: [0, 1, 0],
                params: { duration: 1.6, forwardImpulse: 30, liftImpulse: 8, cooldown: 1.4 },
            },
            {
                id: 'rift_boost_finish',
                type: 'boost',
                pos: [84, 28, 0],
                forward: [1, 0, 0],
                params: { duration: 1.1, forwardImpulse: 40, bonusSpeed: 46, cooldown: 0.8 },
            },
        ],
        playerSpawn: { x: -118, y: 18, z: 0 },
        botSpawns: [
            { x: -112, y: 18, z: -18 },
            { x: -112, y: 18, z: 18 },
            { x: -90, y: 20, z: -34 },
            { x: -90, y: 20, z: 34 },
        ],
        items: [
            { id: 'rift_item_speed_1', type: 'item_battery', pickupType: 'SPEED_UP', x: -36, y: 20, z: -48, weight: 1.4 },
            { id: 'rift_item_speed_2', type: 'item_battery', pickupType: 'SPEED_UP', x: 30, y: 40, z: 52, weight: 1.2 },
            { id: 'rift_item_shield', type: 'item_shield', pickupType: 'SHIELD', x: 58, y: 32, z: -30, weight: 0.8 },
            { id: 'rift_item_rocket', type: 'item_rocket', pickupType: 'ROCKET_WEAK', x: 78, y: 28, z: 24, weight: 0.9 },
        ],
        parcours: {
            enabled: true,
            routeId: 'rift_gauntlet_v1',
            rules: {
                ordered: true,
                resetOnDeath: true,
                resetToLastValid: false,
                maxSegmentTimeMs: 18000,
                cooldownMs: 450,
                wrongOrderCooldownMs: 650,
                errorIndicatorMs: 1400,
                allowLaneAliases: true,
                winnerByParcoursComplete: true,
            },
            checkpoints: [
                { id: 'CP01', type: 'entry', pos: [-108, 18, 0], radius: 6.2, forward: [1, 0, 0] },
                { id: 'CP02', type: 'gate', pos: [-72, 18, 14], radius: 5.6, forward: [1, 0, 0] },
                { id: 'CP03', type: 'tunnel', pos: [-42, 20, -12], radius: 5.4, forward: [1, 0, 0] },
                { id: 'CP04', type: 'gate', pos: [-10, 30, -8], radius: 5.3, forward: [1, 0, 0] },
                { id: 'CP05', type: 'gate', pos: [12, 32, 14], radius: 5.1, forward: [1, 0, 0] },
                { id: 'CP06', type: 'split', pos: [52, 38, -16], radius: 5.5, forward: [1, 0, 0] },
                { id: 'CP06_R', type: 'split', aliasOf: 'CP06', pos: [52, 38, 16], radius: 5.5, forward: [1, 0, 0] },
                { id: 'CP07', type: 'precision', pos: [70, 34, 0], radius: 4.8, forward: [1, 0, 0] },
                { id: 'CP08', type: 'finish_pre', pos: [96, 28, 0], radius: 5.2, forward: [1, 0, 0] },
            ],
            finish: { id: 'FINISH', type: 'finish', pos: [106, 24, 0], radius: 6.4, forward: [1, 0, 0] },
        },
    },
});
