// ============================================
// ObservationSchemaV1.js - fixed observation indices for bridge schema v1
// ============================================
//
// Value ranges per index:
//   0  SPEED_RATIO          [0, 1]     current speed / max speed
//   1  HEALTH_RATIO         [0, 1]     hp / maxHp
//   2  SHIELD_RATIO         [0, 1]     shield / maxShield
//  3-7 WALL_DISTANCE_*      [0, 1]     ray distance / probeDistance (Front/Left/Right/Up/Down)
//   8  TARGET_DISTANCE_RATIO[0, 1]     distance / targetDistanceMax
//   9  TARGET_ALIGNMENT     [-1, 1]    dot product with forward vector
//  10  TARGET_IN_FRONT      {0, 1}     binary
//  11  PRESSURE_LEVEL       [0, 1]     composite threat score
//  12  PROJECTILE_THREAT    {0, 1}     binary
//  13  LOCAL_OPENNESS_RATIO [0, 1]     avg wall distance ratio
//  14  BOOST_ACTIVE         {0, 1}     binary
//  15  INVENTORY_COUNT_RATIO[0, 1]     items / 20
//  16  SELECTED_ITEM_SLOT   [0, 1]     slotIndex / 19 (or -1 if none → 0)
//  17  PLANAR_MODE_ACTIVE   {0, 1}     binary
//  18  MODE_ID              [0, 1]     encoded game mode
//  19  CONTEXT_RESERVED     0          reserved
// 20-39 ITEM_SLOT_00..19    [0, 1]     encoded item type
//
// All values should be in [-1, 1] or [0, 1] when generated by ObservationSystem.
// Trainer clamps to [-10000, 10000] as safety net but expects values in normal range.
// ============================================

export const OBSERVATION_SCHEMA_VERSION = 'v1';
export const OBSERVATION_LENGTH_V1 = 40;

export const SPEED_RATIO = 0;
export const HEALTH_RATIO = 1;
export const SHIELD_RATIO = 2;
export const WALL_DISTANCE_FRONT = 3;
export const WALL_DISTANCE_LEFT = 4;
export const WALL_DISTANCE_RIGHT = 5;
export const WALL_DISTANCE_UP = 6;
export const WALL_DISTANCE_DOWN = 7;
export const TARGET_DISTANCE_RATIO = 8;
export const TARGET_ALIGNMENT = 9;
export const TARGET_IN_FRONT = 10;
export const PRESSURE_LEVEL = 11;
export const PROJECTILE_THREAT = 12;
export const LOCAL_OPENNESS_RATIO = 13;
export const BOOST_ACTIVE = 14;
export const INVENTORY_COUNT_RATIO = 15;
export const SELECTED_ITEM_SLOT = 16;
export const PLANAR_MODE_ACTIVE = 17;
export const MODE_ID = 18;
export const CONTEXT_RESERVED = 19;

export const ITEM_SLOT_00 = 20;
export const ITEM_SLOT_01 = 21;
export const ITEM_SLOT_02 = 22;
export const ITEM_SLOT_03 = 23;
export const ITEM_SLOT_04 = 24;
export const ITEM_SLOT_05 = 25;
export const ITEM_SLOT_06 = 26;
export const ITEM_SLOT_07 = 27;
export const ITEM_SLOT_08 = 28;
export const ITEM_SLOT_09 = 29;
export const ITEM_SLOT_10 = 30;
export const ITEM_SLOT_11 = 31;
export const ITEM_SLOT_12 = 32;
export const ITEM_SLOT_13 = 33;
export const ITEM_SLOT_14 = 34;
export const ITEM_SLOT_15 = 35;
export const ITEM_SLOT_16 = 36;
export const ITEM_SLOT_17 = 37;
export const ITEM_SLOT_18 = 38;
export const ITEM_SLOT_19 = 39;

export const OBSERVATION_INDEX = Object.freeze({
    SPEED_RATIO,
    HEALTH_RATIO,
    SHIELD_RATIO,
    WALL_DISTANCE_FRONT,
    WALL_DISTANCE_LEFT,
    WALL_DISTANCE_RIGHT,
    WALL_DISTANCE_UP,
    WALL_DISTANCE_DOWN,
    TARGET_DISTANCE_RATIO,
    TARGET_ALIGNMENT,
    TARGET_IN_FRONT,
    PRESSURE_LEVEL,
    PROJECTILE_THREAT,
    LOCAL_OPENNESS_RATIO,
    BOOST_ACTIVE,
    INVENTORY_COUNT_RATIO,
    SELECTED_ITEM_SLOT,
    PLANAR_MODE_ACTIVE,
    MODE_ID,
    CONTEXT_RESERVED,
    ITEM_SLOT_00,
    ITEM_SLOT_01,
    ITEM_SLOT_02,
    ITEM_SLOT_03,
    ITEM_SLOT_04,
    ITEM_SLOT_05,
    ITEM_SLOT_06,
    ITEM_SLOT_07,
    ITEM_SLOT_08,
    ITEM_SLOT_09,
    ITEM_SLOT_10,
    ITEM_SLOT_11,
    ITEM_SLOT_12,
    ITEM_SLOT_13,
    ITEM_SLOT_14,
    ITEM_SLOT_15,
    ITEM_SLOT_16,
    ITEM_SLOT_17,
    ITEM_SLOT_18,
    ITEM_SLOT_19,
});

export const OBSERVATION_ITEM_SLOT_INDICES = Object.freeze([
    ITEM_SLOT_00,
    ITEM_SLOT_01,
    ITEM_SLOT_02,
    ITEM_SLOT_03,
    ITEM_SLOT_04,
    ITEM_SLOT_05,
    ITEM_SLOT_06,
    ITEM_SLOT_07,
    ITEM_SLOT_08,
    ITEM_SLOT_09,
    ITEM_SLOT_10,
    ITEM_SLOT_11,
    ITEM_SLOT_12,
    ITEM_SLOT_13,
    ITEM_SLOT_14,
    ITEM_SLOT_15,
    ITEM_SLOT_16,
    ITEM_SLOT_17,
    ITEM_SLOT_18,
    ITEM_SLOT_19,
]);

export function getObservationIndexValues() {
    return Object.values(OBSERVATION_INDEX);
}
