function defineLazyUiRef(target, key, resolver) {
    let resolved = false;
    let cached = null;
    Object.defineProperty(target, key, {
        configurable: true,
        enumerable: true,
        get() {
            if (!resolved) {
                cached = resolver();
                resolved = true;
            }
            return cached;
        },
        set(value) {
            cached = value;
            resolved = true;
        },
    });
}

export function createGameUiRefs(doc = document) {
    const level4CloseButton = doc.getElementById('btn-close-level4') || doc.getElementById('btn-level4-close');
    const ui = {
        mainMenu: doc.getElementById('main-menu'),
        hud: doc.getElementById('hud'),
        p2Hud: doc.getElementById('p2-hud'),
        messageStats: doc.getElementById('message-stats'),
        p1Score: doc.querySelector('#p1-hud .player-score'),
        p2Score: doc.querySelector('#p2-hud .player-score'),
        p1Items: doc.getElementById('p1-items'),
        p2Items: doc.getElementById('p2-items'),
        parcoursHud: doc.getElementById('parcours-hud'),
        parcoursRoute: doc.getElementById('parcours-route'),
        parcoursProgress: doc.getElementById('parcours-progress'),
        parcoursTimer: doc.getElementById('parcours-timer'),
        parcoursStatus: doc.getElementById('parcours-status'),
        messageOverlay: doc.getElementById('message-overlay'),
        messageText: doc.getElementById('message-text'),
        messageSub: doc.getElementById('message-sub'),
        pauseOverlay: doc.getElementById('pause-overlay'),
        pauseResumeButton: doc.getElementById('btn-pause-resume'),
        pauseSettingsButton: doc.getElementById('btn-pause-settings'),
        pauseMenuButton: doc.getElementById('btn-pause-menu'),
        pauseSettingsPanel: doc.getElementById('pause-settings'),
        pauseSettingsBackButton: doc.getElementById('btn-pause-settings-back'),
        pauseAutoRollToggle: doc.getElementById('pause-auto-roll-toggle'),
        pauseInvertP1: doc.getElementById('pause-invert-p1'),
        pauseInvertP2: doc.getElementById('pause-invert-p2'),
        pauseKeybindP1: doc.getElementById('pause-keybind-p1'),
        pauseKeybindP2: doc.getElementById('pause-keybind-p2'),
        pauseKeybindWarning: doc.getElementById('pause-keybind-warning'),
        statusToast: doc.getElementById('status-toast'),
        keybindWarning: doc.getElementById('keybind-warning'),
        menuContext: doc.getElementById('menu-context'),
        menuNav: doc.getElementById('menu-nav'),
        menuPanels: Array.from(doc.querySelectorAll('.submenu-panel')),
        menuNavButtons: Array.from(doc.querySelectorAll('.nav-btn')),
        openExpertButton: doc.getElementById('btn-open-expert'),
        expertQuickLockButton: doc.getElementById('btn-expert-lock-quick'),
        expertLockedState: doc.getElementById('expert-locked-state'),
        expertUnlockedState: doc.getElementById('expert-unlocked-state'),
        expertPasswordInput: doc.getElementById('expert-password-input'),
        expertUnlockButton: doc.getElementById('btn-expert-unlock'),
        expertCancelButton: doc.getElementById('btn-expert-cancel'),
        expertLockButton: doc.getElementById('btn-expert-lock'),
        expertStatus: doc.getElementById('expert-login-status'),
        sessionButtons: Array.from(doc.querySelectorAll('.nav-btn[data-session-type]')),
        modePathButtons: Array.from(doc.querySelectorAll('.mode-path-btn[data-mode-path]')),
        quickStartLastButton: doc.getElementById('btn-quick-last-settings'),
        quickStartEventPlaylistButton: doc.getElementById('btn-quick-event-playlist'),
        quickStartRandomButton: doc.getElementById('btn-quick-random-map'),
        customStepperButtons: Array.from(doc.querySelectorAll('[data-menu-step], [data-menu-step-target]')),
        buildInfo: doc.getElementById('build-info'),
        buildInfoDetail: doc.getElementById('build-info-detail'),
        copyBuildButton: doc.getElementById('btn-copy-build'),
        openDeveloperButton: doc.getElementById('btn-open-developer'),
        openDebugButton: doc.getElementById('btn-open-debug'),
        modeButtons: Array.from(doc.querySelectorAll('.mode-btn[data-mode]')),
        gameModeButtons: Array.from(doc.querySelectorAll('.game-mode-btn')),
        dimensionModeButtons: Array.from(doc.querySelectorAll('.dimension-mode-btn[data-planar-mode]')),
        huntRespawnToggle: doc.getElementById('hunt-respawn-toggle'),
        huntRespawnRow: doc.getElementById('hunt-respawn-row'),
        huntModeHint: doc.getElementById('hunt-mode-hint'),
        startButton: doc.getElementById('btn-start'),
        level3ResetButton: doc.getElementById('btn-level3-reset'),
        openLevel4Button: doc.getElementById('btn-open-level4'),
        closeLevel4Button: level4CloseButton,
        mapSelect: doc.getElementById('map-select'),
        mapSearchInput: doc.getElementById('map-search-input'),
        mapFilterSelect: doc.getElementById('map-filter-select'),
        mapFavoriteToggleButton: doc.getElementById('btn-map-favorite-toggle'),
        mapFavoritesList: doc.getElementById('map-favorites-list'),
        mapRecentList: doc.getElementById('map-recent-list'),
        mapPreview: doc.getElementById('map-preview'),
        mapFieldHint: doc.getElementById('map-field-hint'),
        menuSummary: doc.getElementById('menu-selection-summary'),
        botSlider: doc.getElementById('bot-count'),
        botLabel: doc.getElementById('bot-count-label'),
        botDifficultySelect: doc.getElementById('bot-difficulty'),
        winSlider: doc.getElementById('win-count'),
        winLabel: doc.getElementById('win-count-label'),
        autoRollToggle: doc.getElementById('auto-roll-toggle'),
        invertP1: doc.getElementById('invert-p1'),
        invertP2: doc.getElementById('invert-p2'),
        cockpitCamP1: doc.getElementById('cockpit-cam-p1'),
        cockpitCamP2: doc.getElementById('cockpit-cam-p2'),
        portalsToggle: doc.getElementById('portals-toggle'),
        speedSlider: doc.getElementById('speed-slider'),
        speedLabel: doc.getElementById('speed-label'),
        turnSlider: doc.getElementById('turn-slider'),
        turnLabel: doc.getElementById('turn-label'),
        planeSizeSlider: doc.getElementById('plane-size-slider'),
        planeSizeLabel: doc.getElementById('plane-size-label'),
        trailWidthSlider: doc.getElementById('trail-width-slider'),
        trailWidthLabel: doc.getElementById('trail-width-label'),
        gapSizeSlider: doc.getElementById('gap-size-slider'),
        gapSizeLabel: doc.getElementById('gap-size-label'),
        gapFrequencySlider: doc.getElementById('gap-frequency-slider'),
        gapFrequencyLabel: doc.getElementById('gap-frequency-label'),
        itemAmountSlider: doc.getElementById('item-amount-slider'),
        itemAmountLabel: doc.getElementById('item-amount-label'),
        fireRateSlider: doc.getElementById('fire-rate-slider'),
        fireRateLabel: doc.getElementById('fire-rate-label'),
        lockOnSlider: doc.getElementById('lockon-slider'),
        lockOnLabel: doc.getElementById('lockon-label'),
        mgTrailAimSlider: doc.getElementById('mg-trail-aim-slider'),
        mgTrailAimLabel: doc.getElementById('mg-trail-aim-label'),
        fightPlayerHpSlider: doc.getElementById('fight-player-hp-slider'),
        fightPlayerHpLabel: doc.getElementById('fight-player-hp-label'),
        fightMgDamageSlider: doc.getElementById('fight-mg-damage-slider'),
        fightMgDamageLabel: doc.getElementById('fight-mg-damage-label'),
        fightPlayerHpSetting: doc.getElementById('fight-player-hp-setting'),
        fightMgDamageSetting: doc.getElementById('fight-mg-damage-setting'),
        fightTuningHint: doc.getElementById('fight-tuning-hint'),
        planarModeToggle: doc.getElementById('planar-mode-toggle'),
        portalCountSlider: doc.getElementById('portal-count-slider'),
        portalCountLabel: doc.getElementById('portal-count-label'),
        planarLevelCountSlider: doc.getElementById('planar-level-count-slider'),
        planarLevelCountLabel: doc.getElementById('planar-level-count-label'),
        shadowQualitySlider: doc.getElementById('shadow-quality-slider'),
        shadowQualityLabel: doc.getElementById('shadow-quality-label'),
        recordingProfileSelect: doc.getElementById('recording-profile-select'),
        recordingHudModeSelect: doc.getElementById('recording-hud-mode-select'),
        recordingProfileHint: doc.getElementById('recording-profile-hint'),
        themeModeSelect: doc.getElementById('theme-mode-select'),
        themeFieldHint: doc.getElementById('theme-field-hint'),
        matchFieldHint: doc.getElementById('match-field-hint'),
        startValidationStatus: doc.getElementById('start-validation-status'),
        crosshairP1: doc.getElementById('crosshair-p1'),
        crosshairP2: doc.getElementById('crosshair-p2'),
        keybindP1: doc.getElementById('keybind-p1'),
        keybindP2: doc.getElementById('keybind-p2'),
        keybindGlobal: doc.getElementById('keybind-global'),
        resetKeysButton: doc.getElementById('btn-reset-keys'),
        saveKeysButton: doc.getElementById('btn-save-keys'),
        profileNameInput: doc.getElementById('profile-name'),
        profileSelect: doc.getElementById('profile-select'),
        profileSaveButton: doc.getElementById('btn-profile-save'),
        profileLoadButton: doc.getElementById('btn-profile-load'),
        profileDeleteButton: doc.getElementById('btn-profile-delete'),
        profileDuplicateButton: doc.getElementById('btn-profile-duplicate'),
        profileDefaultButton: doc.getElementById('btn-profile-set-default'),
        profileTransferInput: doc.getElementById('profile-transfer-input'),
        profileExportButton: doc.getElementById('btn-profile-export'),
        profileImportButton: doc.getElementById('btn-profile-import'),
        profileTransferStatus: doc.getElementById('profile-transfer-status'),
        presetSelect: doc.getElementById('preset-select'),
        presetApplyButton: doc.getElementById('btn-preset-apply'),
        presetSaveOpenButton: doc.getElementById('btn-preset-save-open'),
        presetSaveFixedButton: doc.getElementById('btn-preset-save-fixed'),
        presetDeleteButton: doc.getElementById('btn-preset-delete'),
        presetNameInput: doc.getElementById('preset-name'),
        presetStatus: doc.getElementById('preset-status'),
        quickstartPresetButtons: null,
        multiplayerHostButton: doc.getElementById('btn-multiplayer-host'),
        multiplayerJoinButton: doc.getElementById('btn-multiplayer-join'),
        multiplayerReadyToggle: doc.getElementById('multiplayer-ready-toggle'),
        multiplayerStatus: doc.getElementById('multiplayer-status'),
        multiplayerLobbyCodeInput: doc.getElementById('multiplayer-lobby-code'),
        developerModeToggle: doc.getElementById('developer-mode-toggle'),
        developerThemeSelect: doc.getElementById('developer-theme-select'),
        developerVisibilitySelect: doc.getElementById('developer-visibility-select'),
        developerFixedPresetLockToggle: doc.getElementById('developer-fixed-preset-lock-toggle'),
        developerActorSelect: doc.getElementById('developer-actor-select'),
        developerReleasePreviewToggle: doc.getElementById('developer-release-preview-toggle'),
        developerTextIdSelect: doc.getElementById('developer-text-id-select'),
        developerTextOverrideInput: doc.getElementById('developer-text-override-input'),
        developerTextApplyButton: doc.getElementById('btn-developer-text-apply'),
        developerTextClearButton: doc.getElementById('btn-developer-text-clear'),
        developerTelemetryDashboard: doc.getElementById('developer-telemetry-dashboard'),
        developerTelemetryOutput: doc.getElementById('developer-telemetry-output'),
        developerTrainingModeSelect: doc.getElementById('developer-training-mode-select'),
        developerTrainingPlanarToggle: doc.getElementById('developer-training-planar-toggle'),
        developerTrainingMaxStepsInput: doc.getElementById('developer-training-max-steps-input'),
        developerTrainingSeedInput: doc.getElementById('developer-training-seed-input'),
        developerTrainingInventoryInput: doc.getElementById('developer-training-inventory-input'),
        developerTrainingYawSelect: doc.getElementById('developer-training-yaw-select'),
        developerTrainingPitchSelect: doc.getElementById('developer-training-pitch-select'),
        developerTrainingBoostToggle: doc.getElementById('developer-training-boost-toggle'),
        developerTrainingShootMgToggle: doc.getElementById('developer-training-shoot-mg-toggle'),
        developerTrainingShootItemToggle: doc.getElementById('developer-training-shoot-item-toggle'),
        developerTrainingShootItemIndexInput: doc.getElementById('developer-training-shoot-item-index-input'),
        developerTrainingKillsInput: doc.getElementById('developer-training-kills-input'),
        developerTrainingDamageDealtInput: doc.getElementById('developer-training-damage-dealt-input'),
        developerTrainingDamageTakenInput: doc.getElementById('developer-training-damage-taken-input'),
        developerTrainingResetButton: doc.getElementById('btn-developer-training-reset'),
        developerTrainingStepButton: doc.getElementById('btn-developer-training-step'),
        developerTrainingAutoStepButton: doc.getElementById('btn-developer-training-auto-step'),
        developerTrainingRunBatchButton: doc.getElementById('btn-developer-training-run-batch'),
        developerTrainingBatchEpisodesInput: doc.getElementById('developer-training-batch-episodes-input'),
        developerTrainingBatchSeedsInput: doc.getElementById('developer-training-batch-seeds-input'),
        developerTrainingBatchModesInput: doc.getElementById('developer-training-batch-modes-input'),
        developerTrainingRunEvalButton: doc.getElementById('btn-developer-training-run-eval'),
        developerTrainingGateMinReturnInput: doc.getElementById('developer-training-gate-min-return-input'),
        developerTrainingGateMinTerminalRateInput: doc.getElementById('developer-training-gate-min-terminal-rate-input'),
        developerTrainingGateMaxTruncationRateInput: doc.getElementById('developer-training-gate-max-truncation-rate-input'),
        developerTrainingGateMaxInvalidRateInput: doc.getElementById('developer-training-gate-max-invalid-rate-input'),
        developerTrainingGateMaxRuntimeErrorsInput: doc.getElementById('developer-training-gate-max-runtime-errors-input'),
        developerTrainingRunGateButton: doc.getElementById('btn-developer-training-run-gate'),
        developerTrainingOutput: doc.getElementById('developer-training-output'),
        level4Drawer: doc.getElementById('submenu-level4'),
        level4CloseButton: level4CloseButton,
        level4ResetButton: doc.getElementById('btn-level4-reset'),
        level4SectionTabs: null,
        level4SectionPanels: null,
        level4Status: doc.getElementById('level4-status'),
        startSetupRoot: doc.getElementById('start-setup'),
        menuSelectionSummary: doc.getElementById('menu-selection-summary'),
        startRail: doc.querySelector('.start-rail'),
        vehicleSelectP1: doc.getElementById('vehicle-select-p1'),
        vehicleSelectP2: doc.getElementById('vehicle-select-p2'),
        vehicleP2Container: doc.getElementById('vehicle-p2-container'),
        vehicleSearchInput: doc.getElementById('vehicle-search-input'),
        vehicleFilterSelect: doc.getElementById('vehicle-filter-select'),
        vehicleFavoriteToggleButton: doc.getElementById('btn-vehicle-favorite-toggle'),
        vehicleFavoritesList: doc.getElementById('vehicle-favorites-list'),
        vehicleRecentList: doc.getElementById('vehicle-recent-list'),
        vehicleP1FieldHint: doc.getElementById('vehicle-p1-field-hint'),
        vehicleP2FieldHint: doc.getElementById('vehicle-p2-field-hint'),
        vehiclePreviewP1: doc.getElementById('vehicle-preview-p1'),
        vehiclePreviewP2: doc.getElementById('vehicle-preview-p2'),
        multiplayerInlineState: doc.getElementById('multiplayer-inline-stub'),
        multiplayerLobbyState: doc.getElementById('multiplayer-lobby-state'),
        configShareInput: doc.getElementById('config-share-input'),
        configShareStatus: doc.getElementById('config-share-status'),
        exportConfigCodeButton: doc.getElementById('btn-config-export-code'),
        exportConfigJsonButton: doc.getElementById('btn-config-export-json'),
        importConfigButton: doc.getElementById('btn-config-import'),
        openEditorButton: doc.getElementById('btn-open-editor'),
        developerHint: doc.getElementById('developer-hint'),
        developerTrainingItemUsesInput: doc.getElementById('developer-training-item-uses-input'),
        developerTrainingCrashedToggle: doc.getElementById('developer-training-crashed-toggle'),
        developerTrainingStuckToggle: doc.getElementById('developer-training-stuck-toggle'),
        developerTrainingWonToggle: doc.getElementById('developer-training-won-toggle'),
        developerTrainingLostToggle: doc.getElementById('developer-training-lost-toggle'),
        developerTrainingDoneToggle: doc.getElementById('developer-training-done-toggle'),
        developerTrainingTerminalReasonInput: doc.getElementById('developer-training-terminal-reason-input'),
        developerTrainingAutoStepsInput: doc.getElementById('developer-training-auto-steps-input'),
        developerTrainingBridgeModeSelect: doc.getElementById('developer-training-bridge-mode-select'),
        developerTrainingTimeoutMsInput: doc.getElementById('developer-training-timeout-ms-input'),
        vehicleEditorStatus: doc.getElementById('vehicle-editor-status'),
        openVehicleEditorButton: doc.getElementById('btn-open-vehicle-editor'),
    };

    defineLazyUiRef(ui, 'quickstartPresetButtons', () => Array.from(doc.querySelectorAll('[data-preset-id]')));
    defineLazyUiRef(ui, 'debugHints', () => Array.from(doc.querySelectorAll('.debug-hint')));
    defineLazyUiRef(ui, 'startAccordions', () => Array.from(doc.querySelectorAll('[data-start-section]')));
    defineLazyUiRef(ui, 'level4SectionTabs', () => Array.from(doc.querySelectorAll('[data-level4-section-target]')));
    defineLazyUiRef(ui, 'level4SectionPanels', () => Array.from(doc.querySelectorAll('#submenu-level4 [data-level4-section]')));
    defineLazyUiRef(ui, 'legacyLevel4OpenButtons', () => Array.from(doc.querySelectorAll('[data-menu-action="level4-open"]')));

    return ui;
}
