export const LEGACY_MAX_LINES = Object.freeze({
    'src/core/GameDebugApi.js': 650,
    'src/core/GameRuntimeFacade.js': 470,
    'src/core/MediaRecorderSystem.js': 1225,
    'src/core/SettingsManager.js': 585,
    'src/core/config/maps/presets/parcours_pack_v130.js': 620,
    'src/core/main.js': 560,
    'src/entities/ai/training/WebSocketTrainerBridge.js': 700,
    'src/mobile-classic/MobileClassicApp.js': 706,
    'src/shared/runtime/GameRuntimePorts.js': 420,
    'src/ui/MatchFlowUiController.js': 790,
    'src/ui/PauseOverlayController.js': 300,
    'src/ui/TouchInputSource.js': 720,
    'src/ui/UIManager.js': 1225,
});
