"""BT93RR.1 handover lock for the BT93R-Reentry.

This report-only script freezes the green BT93Y.99 handover and the active
retrain-lineage package before the reentry artifact probe. It does not train,
evaluate, apply fixes, consume holdout data, create candidates, or touch
runtime surfaces.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path
from typing import Any, Iterable, Mapping


REPO_ROOT = Path(__file__).resolve().parents[2]
PPO_ROOT = REPO_ROOT / "data" / "training" / "ppo"
BT93R_REENTRY_ROOT = PPO_ROOT / "bt93r_reentry"
BT93R_ROOT = PPO_ROOT / "bt93r"
BT93X_ROOT = PPO_ROOT / "bt93x"
BT93Y_ROOT = PPO_ROOT / "bt93y"
OUTPUT_PATH = BT93R_REENTRY_ROOT / "bt93r_reentry_handover_lock_report.json"

SOURCE_PATHS: dict[str, tuple[Path, str, Mapping[str, Any]]] = {
    "bt93yClosureGate": (
        BT93Y_ROOT / "bt93y_closure_gate_report.json",
        "BT93Y.99 closure gate",
        {"phaseId": "93Y.99", "resultClass": "retrain-lineage-ready-bt93r-reentry-ready"},
    ),
    "bt93yReentryManifest": (
        BT93Y_ROOT / "bt93r_reentry_manifest.json",
        "BT93Y.5 BT93R-Reentry manifest",
        {"phaseId": "93Y.5", "resultClass": "retrain-lineage-ready-bt93r-reentry-ready"},
    ),
    "bt93yReentryGate": (
        BT93Y_ROOT / "bt93r_reentry_gate_report.json",
        "BT93Y.5 BT93R-Reentry gate",
        {"phaseId": "93Y.5", "resultClass": "retrain-lineage-ready-bt93r-reentry-ready"},
    ),
    "bt93yRetrainLineage": (
        BT93Y_ROOT / "retrain_lineage_manifest.json",
        "BT93Y.3 active retrain-lineage manifest",
        {"phaseId": "93Y.3", "resultClass": "retrain-lineage-ready"},
    ),
    "bt93yReplacementPolicyLock": (
        BT93Y_ROOT / "replacement_policy_lock_report.json",
        "BT93Y.4 replacement-policy lock",
        {"phaseId": "93Y.4", "resultClass": "replacement-policy-approved"},
    ),
    "bt93xReplacementPolicyDecision": (
        BT93X_ROOT / "replacement_policy_decision.json",
        "BT93X replacement-policy decision generated by BT93Y.4",
        {"phaseId": "93Y.4", "resultClass": "replacement-policy-approved"},
    ),
    "bt93rHistoricalClosure": (
        BT93R_ROOT / "bt93r_closure_gate_report.json",
        "Historical red BT93R.99 closure",
        {"phaseId": "93R.99", "resultClass": "model-artifact-missing"},
    ),
    "bt93rHistoricalArtifactProbe": (
        BT93R_ROOT / "policy_artifact_report.json",
        "Historical red BT93R artifact probe",
        {"phaseId": "93R.2", "resultClass": "policy-evidence-invalid"},
    ),
    "bt93x0ComparatorPreflight": (
        BT93X_ROOT / "early_comparator_preflight_report.json",
        "BT93X.0 read-only comparator preflight",
        {"phaseId": "93X.0", "comparisonPolicyDecision": "dqn-anchor-blocked"},
    ),
}

BLOCKED_ACTIONS = [
    "BT93S claim before BT93R-Reentry.99 in R-Allowlist",
    "BT93O claim",
    "BT93P claim",
    "BT94A claim",
    "candidate run",
    "freeze candidate",
    "holdout consumption",
    "promote",
    "rollout",
    "PPO-Validate signal",
    "BT95 handoff signal",
    "productive runtime integration",
    "reward/action/telemetry/safety fix during 93RR.1",
]


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _json_text(payload: Mapping[str, Any]) -> str:
    return f"{json.dumps(payload, indent=2, sort_keys=True)}\n"


def _read_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_json_text(payload), encoding="utf-8")


def _rel(path: Path | None) -> str | None:
    if path is None:
        return None
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _sha256_file(path: Path | None) -> str | None:
    if path is None or not path.is_file():
        return None
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _git_output(args: list[str]) -> str:
    result = subprocess.run(args, cwd=REPO_ROOT, text=True, capture_output=True, check=False)
    return result.stdout.strip() if result.returncode == 0 else ""


def _git_lines(args: list[str]) -> list[str]:
    return [line.strip().replace("\\", "/") for line in _git_output(args).splitlines() if line.strip()]


def _tracked_files(paths: Iterable[Path | None]) -> set[str]:
    rel_paths = [_rel(path) for path in paths if path is not None]
    rel_paths = [path for path in rel_paths if path]
    if not rel_paths:
        return set()
    return set(_git_lines(["git", "ls-files", "--", *rel_paths]))


def _get(mapping: Mapping[str, Any] | None, *keys: str) -> Any:
    current: Any = mapping
    for key in keys:
        if not isinstance(current, Mapping):
            return None
        current = current.get(key)
    return current


def _expected_ok(payload: Mapping[str, Any], expected: Mapping[str, Any]) -> bool:
    return all(_get(payload, *key.split(".")) == value for key, value in expected.items())


def _source_artifact(key: str, path: Path, role: str, expected: Mapping[str, Any], tracked: set[str]) -> dict[str, Any]:
    payload = _read_json(path)
    rel_path = _rel(path)
    return {
        "sourceKey": key,
        "path": rel_path,
        "role": role,
        "exists": path.exists(),
        "isFile": path.is_file(),
        "tracked": rel_path in tracked if rel_path else False,
        "fresh": bool(path.is_file() and rel_path in tracked and _expected_ok(payload, expected)),
        "sha256": _sha256_file(path),
        "sizeBytes": path.stat().st_size if path.is_file() else None,
        "schemaVersion": payload.get("schemaVersion") if payload else None,
        "blockId": payload.get("blockId") if payload else None,
        "phaseId": payload.get("phaseId") if payload else None,
        "resultClass": payload.get("resultClass") if payload else None,
        "ok": payload.get("ok") if payload else None,
        "expectedFields": dict(expected),
        "actualFields": {key_name: _get(payload, *key_name.split(".")) for key_name in expected},
    }


def _guardrails() -> dict[str, Any]:
    return {
        "diagnosticOnly": True,
        "trainingStarted": False,
        "newEvalRunStarted": False,
        "fixApplied": False,
        "candidateRun": False,
        "freezeCandidate": False,
        "holdoutUsed": False,
        "bt93sClaimAllowed": False,
        "bt93oClaimAllowed": False,
        "bt93pClaimAllowed": False,
        "bt94aClaimAllowed": False,
        "candidateRunsAllowed": False,
        "candidateFreezeAllowed": False,
        "qualityClaimAllowed": False,
        "promoteAllowed": False,
        "rolloutAllowed": False,
        "ppoValidateSignal": False,
        "bt95HandoffSignal": False,
        "productiveRuntimeChanged": False,
        "runtimeSurfacesTouched": [],
    }


def _claim_flags() -> dict[str, bool]:
    return {
        "bt93sClaimAllowed": False,
        "bt93oClaimAllowed": False,
        "bt93pClaimAllowed": False,
        "bt94aClaimAllowed": False,
        "candidateRunsAllowed": False,
        "candidateFreezeAllowed": False,
        "holdoutConsumptionAllowed": False,
        "promoteAllowed": False,
        "rolloutAllowed": False,
    }


def _package_summary(retrain_manifest: Mapping[str, Any]) -> dict[str, Any]:
    active = retrain_manifest.get("activeLineage")
    active = active if isinstance(active, Mapping) else retrain_manifest
    model_package = active.get("modelPackage") if isinstance(active.get("modelPackage"), Mapping) else {}
    return {
        "lineageId": active.get("lineageId") or retrain_manifest.get("lineageId"),
        "lineageKind": active.get("lineageKind") or retrain_manifest.get("lineageKind"),
        "notBt93nLineage": active.get("notBt93nLineage") or retrain_manifest.get("lineageKind") == "new-retrain-lineage-not-bt93n",
        "ready": active.get("ready", retrain_manifest.get("ok")),
        "matrixId": retrain_manifest.get("matrixId"),
        "matrixHash": retrain_manifest.get("matrixHash"),
        "rewardProfileId": retrain_manifest.get("rewardProfileId"),
        "semanticWindow": retrain_manifest.get("semanticWindow"),
        "actionSurfaceId": _get(retrain_manifest, "actionSurface", "surfaceId"),
        "actionSurfaceSha256": _get(retrain_manifest, "actionSurface", "sourceSha256"),
        "modelPackage": {
            key: {
                "path": _get(model_package, key, "path"),
                "sha256": _get(model_package, key, "sha256"),
                "tracked": _get(model_package, key, "tracked"),
                "exists": _get(model_package, key, "exists"),
            }
            for key in ("model", "config", "vecnormalize", "optimizerState", "artifactManifest", "trainingReport")
        },
        "sampleCounts": retrain_manifest.get("sampleCounts") or _get(active, "packageManifest", "summary", "sampleCounts"),
    }


def build_report() -> dict[str, Any]:
    source_paths = [path for path, _role, _expected in SOURCE_PATHS.values()]
    tracked = _tracked_files(source_paths)
    sources = [
        _source_artifact(key, path, role, expected, tracked)
        for key, (path, role, expected) in SOURCE_PATHS.items()
    ]
    by_key = {source["sourceKey"]: source for source in sources}
    closure = _read_json(SOURCE_PATHS["bt93yClosureGate"][0])
    reentry_manifest = _read_json(SOURCE_PATHS["bt93yReentryManifest"][0])
    retrain_manifest = _read_json(SOURCE_PATHS["bt93yRetrainLineage"][0])
    replacement_policy = _read_json(SOURCE_PATHS["bt93xReplacementPolicyDecision"][0])

    source_files_ready = all(source["fresh"] for source in sources)
    active_lineage = _package_summary(retrain_manifest)
    bt93y_green = (
        closure.get("resultClass") == "retrain-lineage-ready-bt93r-reentry-ready"
        and _get(closure, "claimFlags", "bt93rReentryAllowed") is True
    )
    reentry_ready = (
        reentry_manifest.get("resultClass") == "retrain-lineage-ready-bt93r-reentry-ready"
        and _get(reentry_manifest, "activeLineage", "ready") is True
    )
    result_class = "reentry-handover-lock-green" if source_files_ready and bt93y_green and reentry_ready else "measurement-invalid"
    ok = result_class == "reentry-handover-lock-green"

    return {
        "schemaVersion": "bt93rr-reentry-handover-lock-report-v1",
        "ok": ok,
        "generatedAt": _utc_now(),
        "generatedBy": "python/scripts/bt93r_reentry_handover_lock.py",
        "blockId": "BT93RR",
        "phaseId": "93RR.1",
        "resultClass": result_class,
        "git": {
            "branch": _git_output(["git", "branch", "--show-current"]),
            "sha": _git_output(["git", "rev-parse", "HEAD"]),
        },
        "activeLineage": active_lineage,
        "matrixId": active_lineage.get("matrixId") or _get(reentry_manifest, "matrixContract", "matrixId"),
        "matrixHash": active_lineage.get("matrixHash") or _get(reentry_manifest, "matrixContract", "matrixHash"),
        "actionSurfaceId": active_lineage.get("actionSurfaceId"),
        "actionSurfaceSha256": active_lineage.get("actionSurfaceSha256"),
        "rewardProfileId": active_lineage.get("rewardProfileId"),
        "semanticWindow": active_lineage.get("semanticWindow"),
        "replacementPolicy": {
            "policyId": replacement_policy.get("policyId") or _get(closure, "replacementPolicy", "policyId"),
            "owner": replacement_policy.get("owner") or _get(closure, "replacementPolicy", "owner"),
            "decision": replacement_policy.get("decision") or _get(closure, "replacementPolicy", "decision"),
            "historicalDqnBotReportsUse": replacement_policy.get("historicalDqnBotReportsUse"),
        },
        "historicalTruth": {
            "bt93rClosure": {
                "path": by_key["bt93rHistoricalClosure"]["path"],
                "resultClass": by_key["bt93rHistoricalClosure"]["resultClass"],
                "preserved": True,
            },
            "bt93x0Comparator": {
                "path": by_key["bt93x0ComparatorPreflight"]["path"],
                "comparisonPolicyDecision": by_key["bt93x0ComparatorPreflight"]["actualFields"].get("comparisonPolicyDecision"),
                "readOnlyContext": True,
            },
        },
        "allowedResultClasses": {
            "greenFinal": [
                "policy-collapse-green",
                "decoder-fix-counterprobe-green",
                "normalize-fix-counterprobe-green",
                "eval-mode-bug-fixed-counterprobe-green",
            ],
            "redFinal": [
                "policy-collapse-active",
                "policy-evidence-invalid",
                "normalize-mismatch",
                "model-artifact-missing",
                "measurement-invalid",
            ],
            "phase93rr1": [
                "reentry-handover-lock-green",
                "artifact-probe-green",
                "policy-evidence-invalid",
                "measurement-invalid",
            ],
        },
        "phaseCoverage": {
            "93RR.1.1": source_files_ready and bt93y_green and reentry_ready,
            "DoD.RR1": bool(active_lineage.get("lineageId") and active_lineage.get("matrixId") and active_lineage.get("actionSurfaceId")),
        },
        "guardrails": _guardrails(),
        "claimFlags": _claim_flags(),
        "sampleCounts": {
            "newTrainingEpisodes": 0,
            "newEvalEpisodes": 0,
            "holdoutEpisodes": 0,
            "steps": 0,
            "notApplicableReason": "93RR.1 handover lock over existing versioned BT93Y/R/X evidence.",
        },
        "sourceArtifacts": sources,
        "sourceFilesReady": source_files_ready,
        "allowNext": ["93RR.1 artifact probe"] if ok else [],
        "opensNext": ["93RR.1 artifact probe"] if ok else [],
        "blocksNext": BLOCKED_ACTIONS,
        "summary": {
            "finalResult": result_class,
            "bt93rReentryAllowedByBt93y99": bt93y_green,
            "activeLineageReady": reentry_ready,
            "nextBestAction": "Run only 93RR.1 artifact probe against bt93y-retrain-lineage-v1." if ok else "Stop BT93RR.1; handover evidence is not fresh.",
            "bt93sStartDecision": "blocked until BT93R-Reentry.99 in R-Allowlist",
            "bt93oStartDecision": "blocked",
            "bt93pStartDecision": "blocked",
            "bt94aStartDecision": "blocked",
        },
        "commands": {
            "write": "python python/scripts/bt93r_reentry_handover_lock.py --write-report",
            "metaGate": "npm.cmd run gates:pre-commit",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-report", action="store_true")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()

    report = build_report()
    if args.write_report:
        _write_json(args.output.resolve(), report)
    print(
        json.dumps(
            {
                "ok": report["ok"],
                "resultClass": report["resultClass"],
                "phaseCoverage": report["phaseCoverage"],
                "output": _rel(args.output.resolve()),
                "opensNext": report["opensNext"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
