"""BT93Y.99 closure gate.

Closes BT93Y from versioned lineage, replacement-policy, and reentry-package
evidence only. A green closure may open exactly the new BT93R-Reentry
diagnostic probe path; it must not open BT93S/O/P/94A, candidate, freeze,
holdout, promote, rollout, PPO-Validate, BT95 handoff, or productive runtime
signals.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path
from typing import Any, Iterable, Mapping


REPO_ROOT = Path(__file__).resolve().parents[2]
PPO_ROOT = REPO_ROOT / "data" / "training" / "ppo"
BT93Y_ROOT = PPO_ROOT / "bt93y"
BT93X_ROOT = PPO_ROOT / "bt93x"

CLOSURE_REPORT_PATH = BT93Y_ROOT / "bt93y_closure_gate_report.json"
HANDOVER_PACKAGE_PATH = BT93Y_ROOT / "bt93y_handover_package.json"

GREEN_RESULT_CLASSES = {
    "exact-lineage-restored-bt93r-reentry-ready",
    "retrain-lineage-ready-bt93r-reentry-ready",
}
RED_RESULT_CLASSES = {
    "lineage-recovery-blocked",
    "lineage-package-invalid",
    "retrain-lineage-not-comparable",
    "replacement-policy-decision-missing",
    "bt93r-reentry-blocked",
    "measurement-invalid",
}
REPLACEMENT_POLICY_ID = "bt93x-rcp1-same-matrix-control-suite-no-bt11"

SOURCE_SPECS: dict[str, tuple[Path, str, Mapping[str, Any]]] = {
    "bt93yDecisionLock": (
        BT93Y_ROOT / "lineage_recovery_decision_lock.json",
        "BT93Y.1 lineage and replacement-policy decision lock",
        {"phaseId": "93Y.1", "resultClass": "lineage-recovery-lock-green"},
    ),
    "bt93yExactLineageInventory": (
        BT93Y_ROOT / "exact_lineage_inventory_report.json",
        "BT93Y.2 exact lineage inventory and negative evidence",
        {"phaseId": "93Y.2", "resultClass": "exact-lineage-unavailable"},
    ),
    "bt93yExactLineageLoaderSmoke": (
        BT93Y_ROOT / "exact_lineage_loader_smoke_report.json",
        "BT93Y.2 exact lineage loader-smoke record",
        {"phaseId": "93Y.2", "resultClass": "exact-lineage-unavailable"},
    ),
    "bt93yExactLineageManifest": (
        BT93Y_ROOT / "exact_lineage_manifest.json",
        "BT93Y.2 exact lineage manifest",
        {"phaseId": "93Y.2", "resultClass": "exact-lineage-unavailable"},
    ),
    "bt93yRetrainStartContract": (
        BT93Y_ROOT / "retrain_start_contract.json",
        "BT93Y.3 retrain start contract",
        {"phaseId": "93Y.3", "resultClass": "retrain-start-contract-locked"},
    ),
    "bt93yRetrainLineageManifest": (
        BT93Y_ROOT / "retrain_lineage_manifest.json",
        "BT93Y.3 retrain lineage manifest",
        {"phaseId": "93Y.3", "resultClass": "retrain-lineage-ready"},
    ),
    "bt93yRetrainLoaderSmoke": (
        BT93Y_ROOT / "retrain_loader_smoke_report.json",
        "BT93Y.3 retrain loader smoke",
        {"phaseId": "93Y.3", "resultClass": "retrain-loader-smoke-green"},
    ),
    "bt93yRetrainPolicyProbe": (
        BT93Y_ROOT / "retrain_policy_probe_report.json",
        "BT93Y.3 retrain policy probe",
        {"phaseId": "93Y.3", "resultClass": "retrain-lineage-ready"},
    ),
    "bt93yReplacementPolicyLock": (
        BT93Y_ROOT / "replacement_policy_lock_report.json",
        "BT93Y.4 replacement-policy lock",
        {"phaseId": "93Y.4", "resultClass": "replacement-policy-approved"},
    ),
    "bt93xReplacementPolicyDecision": (
        BT93X_ROOT / "replacement_policy_decision.json",
        "BT93X replacement-policy decision generated by BT93Y.4",
        {
            "phaseId": "93Y.4",
            "resultClass": "replacement-policy-approved",
            "owner": "user",
            "decision": "approved",
            "policyId": REPLACEMENT_POLICY_ID,
        },
    ),
    "bt93yReentryManifest": (
        BT93Y_ROOT / "bt93r_reentry_manifest.json",
        "BT93Y.5 BT93R-Reentry manifest",
        {"phaseId": "93Y.5", "resultClass": GREEN_RESULT_CLASSES},
    ),
    "bt93yReentryGateReport": (
        BT93Y_ROOT / "bt93r_reentry_gate_report.json",
        "BT93Y.5 BT93R-Reentry gate report",
        {"phaseId": "93Y.5", "resultClass": GREEN_RESULT_CLASSES},
    ),
}

REENTRY_ONLY_NEXT = ["BT93R-Reentry artifact-probe/root-cause/counterprobe claim"]
BLOCKED_NEXT = [
    "BT93S claim before BT93R-Reentry.99 in R-Allowlist",
    "BT93O claim",
    "BT93P claim",
    "BT94A claim",
    "candidate run",
    "freeze candidate",
    "holdout consumption",
    "promote",
    "rollout",
    "PPO-Validate signal",
    "BT95 handoff signal",
    "productive runtime integration",
    "50k/100k/200k/500k/1M extension",
]


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _rel(path: Path | None) -> str | None:
    if path is None:
        return None
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _read_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _json_text(payload: Mapping[str, Any]) -> str:
    return f"{json.dumps(payload, indent=2, sort_keys=True)}\n"


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_json_text(payload), encoding="utf-8")


def _sha256_file(path: Path | None) -> str | None:
    if path is None or not path.is_file():
        return None
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _sha256_payload(payload: Mapping[str, Any]) -> str:
    return sha256(_json_text(payload).encode("utf-8")).hexdigest()


def _git_output(args: list[str]) -> str:
    result = subprocess.run(args, cwd=REPO_ROOT, text=True, capture_output=True, check=False)
    return result.stdout.strip() if result.returncode == 0 else ""


def _git_lines(args: list[str]) -> list[str]:
    return [line.strip().replace("\\", "/") for line in _git_output(args).splitlines() if line.strip()]


def _tracked_files(paths: Iterable[Path | None]) -> set[str]:
    rel_paths = [_rel(path) for path in paths if path is not None]
    rel_paths = [path for path in rel_paths if path]
    if not rel_paths:
        return set()
    return set(_git_lines(["git", "ls-files", "--", *rel_paths]))


def _get(mapping: Mapping[str, Any] | None, *keys: str) -> Any:
    current: Any = mapping
    for key in keys:
        if not isinstance(current, Mapping):
            return None
        current = current.get(key)
    return current


def _expected_matches(actual: Any, expected: Any) -> bool:
    if isinstance(expected, (set, list, tuple)):
        return actual in expected
    return actual == expected


def _artifact(path: Path, role: str, tracked: set[str], expected: Mapping[str, Any]) -> dict[str, Any]:
    payload = _read_json(path) if path.suffix == ".json" else {}
    rel_path = _rel(path)
    expected_fields = dict(expected)
    actual_fields = {key: _get(payload, *key.split(".")) for key in expected_fields}
    expected_ok = all(_expected_matches(actual_fields[key], value) for key, value in expected_fields.items())
    expected_report_fields = {
        key: sorted(value) if isinstance(value, set) else value
        for key, value in expected_fields.items()
    }
    tracked_ok = rel_path in tracked if rel_path else False
    return {
        "path": rel_path,
        "role": role,
        "exists": path.exists(),
        "isFile": path.is_file(),
        "tracked": tracked_ok,
        "fresh": bool(path.is_file() and tracked_ok and expected_ok),
        "sha256": _sha256_file(path),
        "sizeBytes": path.stat().st_size if path.is_file() else None,
        "schemaVersion": payload.get("schemaVersion") if payload else None,
        "blockId": payload.get("blockId") if payload else None,
        "phaseId": payload.get("phaseId") if payload else None,
        "resultClass": payload.get("resultClass") if payload else None,
        "ok": payload.get("ok") if payload else None,
        "expectedFields": expected_report_fields,
        "actualFields": actual_fields,
    }


def _source_artifacts() -> list[dict[str, Any]]:
    tracked = _tracked_files([path for path, _role, _expected in SOURCE_SPECS.values()])
    return [
        {"sourceKey": key, **_artifact(path, role, tracked, expected)}
        for key, (path, role, expected) in SOURCE_SPECS.items()
    ]


def _claim_flags(*, bt93r_reentry_allowed: bool) -> dict[str, bool]:
    return {
        "bt93rReentryAllowed": bt93r_reentry_allowed,
        "bt93sClaimAllowed": False,
        "bt93oClaimAllowed": False,
        "bt93pClaimAllowed": False,
        "bt94aClaimAllowed": False,
        "candidateRunsAllowed": False,
        "candidateFreezeAllowed": False,
        "holdoutConsumptionAllowed": False,
        "promoteAllowed": False,
        "rolloutAllowed": False,
    }


def _guardrails(*, bt93r_reentry_allowed: bool) -> dict[str, Any]:
    return {
        "diagnosticOnly": True,
        "trainingStarted": False,
        "newEvalRunStarted": False,
        "fixApplied": False,
        "candidateRun": False,
        "freezeCandidate": False,
        "holdoutUsed": False,
        "promotionAllowed": False,
        "rolloutAllowed": False,
        "ppoValidateSignal": False,
        "bt95HandoffSignal": False,
        "productiveRuntimeChanged": False,
        "runtimeSurfacesTouched": [],
        **_claim_flags(bt93r_reentry_allowed=bt93r_reentry_allowed),
    }


def _active_lineage(exact_manifest: Mapping[str, Any], retrain_manifest: Mapping[str, Any]) -> dict[str, Any]:
    exact_ready = exact_manifest.get("resultClass") in {
        "exact-bt93n-lineage-restored",
        "exact-lineage-restored",
        "exact-lineage-restored-bt93r-reentry-ready",
    }
    retrain_ready = retrain_manifest.get("resultClass") == "retrain-lineage-ready"
    active_count = int(exact_ready) + int(retrain_ready)
    if exact_ready:
        return {
            "activeCount": active_count,
            "ready": active_count == 1,
            "sourceKind": "exact-bt93n-lineage-restored",
            "sourcePath": _rel(BT93Y_ROOT / "exact_lineage_manifest.json"),
            "sourceResultClass": exact_manifest.get("resultClass"),
            "lineageId": exact_manifest.get("lineageId") or "exact-bt93n-lineage",
            "lineageKind": exact_manifest.get("lineageKind") or "exact-bt93n-lineage-restored",
            "notBt93nLineage": False,
        }
    return {
        "activeCount": active_count,
        "ready": active_count == 1 and retrain_ready,
        "sourceKind": "retrain-lineage-ready",
        "sourcePath": _rel(BT93Y_ROOT / "retrain_lineage_manifest.json"),
        "sourceResultClass": retrain_manifest.get("resultClass"),
        "lineageId": retrain_manifest.get("lineageId"),
        "lineageKind": retrain_manifest.get("lineageKind"),
        "notBt93nLineage": True,
    }


def _result_class(active_lineage: Mapping[str, Any], reentry_gate: Mapping[str, Any]) -> str:
    if not active_lineage.get("ready") or reentry_gate.get("ok") is not True:
        return "bt93r-reentry-blocked"
    if active_lineage.get("sourceKind") == "exact-bt93n-lineage-restored":
        return "exact-lineage-restored-bt93r-reentry-ready"
    if active_lineage.get("sourceKind") == "retrain-lineage-ready":
        return "retrain-lineage-ready-bt93r-reentry-ready"
    return "bt93r-reentry-blocked"


def _phase_coverage(
    *,
    source_files_ready: bool,
    active_lineage: Mapping[str, Any],
    replacement_decision: Mapping[str, Any],
    reentry_gate: Mapping[str, Any],
    result_class: str,
    guardrails: Mapping[str, Any],
) -> dict[str, bool]:
    other_claims_closed = all(
        guardrails[key] is False
        for key in [
            "bt93sClaimAllowed",
            "bt93oClaimAllowed",
            "bt93pClaimAllowed",
            "bt94aClaimAllowed",
            "candidateRunsAllowed",
            "candidateFreezeAllowed",
            "holdoutConsumptionAllowed",
            "promoteAllowed",
            "rolloutAllowed",
        ]
    )
    return {
        "93Y.99.1": source_files_ready,
        "93Y.99.2": active_lineage.get("ready") is True and active_lineage.get("activeCount") == 1,
        "93Y.99.3": replacement_decision.get("owner") == "user"
        and replacement_decision.get("decision") == "approved"
        and replacement_decision.get("policyId") == REPLACEMENT_POLICY_ID,
        "93Y.99.4": result_class in GREEN_RESULT_CLASSES
        and guardrails.get("bt93rReentryAllowed") is True
        and reentry_gate.get("ok") is True,
        "93Y.99.5": other_claims_closed,
        "93Y.99.6": True,
    }


def build_reports() -> tuple[dict[str, Any], dict[str, Any]]:
    generated_at = _utc_now()
    source_artifacts = _source_artifacts()
    payloads = {key: _read_json(path) for key, (path, _role, _expected) in SOURCE_SPECS.items()}

    exact_manifest = payloads["bt93yExactLineageManifest"]
    retrain_manifest = payloads["bt93yRetrainLineageManifest"]
    replacement_decision = payloads["bt93xReplacementPolicyDecision"]
    reentry_gate = payloads["bt93yReentryGateReport"]
    reentry_manifest = payloads["bt93yReentryManifest"]
    active_lineage = _active_lineage(exact_manifest, retrain_manifest)
    result_class = _result_class(active_lineage, reentry_gate)
    source_files_ready = all(item["exists"] and item["isFile"] and item["tracked"] and item["fresh"] for item in source_artifacts)
    bt93r_reentry_allowed = source_files_ready and result_class in GREEN_RESULT_CLASSES
    guardrails = _guardrails(bt93r_reentry_allowed=bt93r_reentry_allowed)
    claim_flags = _claim_flags(bt93r_reentry_allowed=bt93r_reentry_allowed)
    phase_coverage = _phase_coverage(
        source_files_ready=source_files_ready,
        active_lineage=active_lineage,
        replacement_decision=replacement_decision,
        reentry_gate=reentry_gate,
        result_class=result_class,
        guardrails=guardrails,
    )
    dod_coverage = {
        "DoD.Y6": bt93r_reentry_allowed and result_class in GREEN_RESULT_CLASSES,
        "DoD.Y7": all(not guardrails[key] for key in [
            "bt93sClaimAllowed",
            "bt93oClaimAllowed",
            "bt93pClaimAllowed",
            "bt94aClaimAllowed",
            "candidateRunsAllowed",
            "candidateFreezeAllowed",
            "holdoutConsumptionAllowed",
            "promoteAllowed",
            "rolloutAllowed",
            "ppoValidateSignal",
            "bt95HandoffSignal",
            "productiveRuntimeChanged",
        ]),
    }
    ok = (
        source_files_ready
        and result_class in GREEN_RESULT_CLASSES
        and all(phase_coverage.values())
        and all(dod_coverage.values())
    )
    if not ok and result_class in GREEN_RESULT_CLASSES:
        result_class = "bt93r-reentry-blocked"
        bt93r_reentry_allowed = False
        guardrails = _guardrails(bt93r_reentry_allowed=False)
        claim_flags = _claim_flags(bt93r_reentry_allowed=False)

    git_info = {
        "branch": _git_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]),
        "sha": _git_output(["git", "rev-parse", "HEAD"]),
        "mergeBaseOriginBotTraining": _git_output(["git", "merge-base", "HEAD", "origin/bot-training"]),
    }
    generated_artifacts = {
        "closureGateReport": _rel(CLOSURE_REPORT_PATH),
        "handoverPackage": _rel(HANDOVER_PACKAGE_PATH),
    }
    blocking_status = {
        "bt93rReentryBlocked": not bt93r_reentry_allowed,
        "bt93sBlockedUntil": "BT93R-Reentry.99 in R-Allowlist",
        "bt93oBlockedUntil": "BT93W.99=bt93o-precondition-green",
        "bt93pBlockedUntil": "BT93O.99=bt93o-quality-green and BT93X.99=bt93p-starttruth-green",
        "bt94aBlockedUntil": "BT93P.4=BT94A-ready plus green no-start gate",
        "candidateFreezePromoteRolloutBlocked": True,
    }
    sample_counts = {
        "newTrainingEpisodes": 0,
        "newEvalEpisodes": 0,
        "holdoutEpisodes": 0,
        "steps": 0,
        "notApplicableReason": "93Y.99 is a closure gate over existing versioned evidence.",
    }
    recommendations = [
        {
            "rank": 1,
            "action": "Claim only BT93R-Reentry as the next /fix-planung task.",
            "why": "BT93Y.99 opens exactly the artifact-probe/root-cause/counterprobe path for the active retrain lineage.",
        },
        {
            "rank": 2,
            "action": "Keep BT93S blocked until the new BT93R-Reentry.99 reaches the R-Allowlist.",
            "why": "Action-selection work needs a concrete policy-collapse class and counterprobe result first.",
        },
        {
            "rank": 3,
            "action": "Do not start BT93O, BT93P, BT94A, candidate, freeze, holdout, promote, rollout, or PPO-Validate work.",
            "why": "Those gates still require R-Allowlist, S/T/U/V/W, O-quality, X-starttruth, and P.4 evidence.",
        },
    ]

    closure = {
        "schemaVersion": "bt93y-closure-gate-report-v1",
        "ok": ok,
        "generatedAt": generated_at,
        "generatedBy": "python/scripts/bt93y_closure_gate.py",
        "git": git_info,
        "blockId": "BT93Y",
        "phaseId": "93Y.99",
        "resultClass": result_class if ok else "bt93r-reentry-blocked",
        "greenResultClasses": sorted(GREEN_RESULT_CLASSES),
        "redResultClasses": sorted(RED_RESULT_CLASSES),
        "sourceArtifacts": source_artifacts,
        "generatedArtifacts": generated_artifacts,
        "sourceFilesReady": source_files_ready,
        "activeLineage": active_lineage,
        "replacementPolicy": {
            "owner": replacement_decision.get("owner"),
            "decision": replacement_decision.get("decision"),
            "policyId": replacement_decision.get("policyId"),
            "historicalDqnBotReportsUse": _get(
                replacement_decision,
                "historicalEvidencePolicy",
                "historicalDqnBotReportsUse",
            ),
            "scope": replacement_decision.get("scope") or _get(replacement_decision, "replacementPolicy", "scope"),
        },
        "reentryPackage": {
            "manifestPath": _rel(BT93Y_ROOT / "bt93r_reentry_manifest.json"),
            "gateReportPath": _rel(BT93Y_ROOT / "bt93r_reentry_gate_report.json"),
            "manifestResultClass": reentry_manifest.get("resultClass"),
            "gateResultClass": reentry_gate.get("resultClass"),
            "stageOrder": _get(reentry_manifest, "reentryPlan", "stageOrder"),
            "targetBlock": _get(reentry_manifest, "reentryPlan", "targetBlock"),
        },
        "phaseCoverage": phase_coverage,
        "dodCoverage": dod_coverage,
        "claimFlags": claim_flags,
        "guardrails": guardrails,
        "blockingStatus": blocking_status,
        "allowNext": REENTRY_ONLY_NEXT if ok else [],
        "opensNext": ["BT93R-Reentry"] if ok else [],
        "blocksNext": list(BLOCKED_NEXT),
        "sampleCounts": sample_counts,
        "recommendations": recommendations,
        "summary": {
            "finalResult": result_class if ok else "bt93r-reentry-blocked",
            "bt93rReentryAllowed": bt93r_reentry_allowed,
            "nextBestAction": "Claim BT93R-Reentry only; BT93S/O/P/94A remain blocked.",
            "blockersForNextFixPlanung": [] if ok else ["bt93r-reentry-blocked"],
            "remainingBlockersAfterNextFixPlanung": [
                "BT93S still needs BT93R-Reentry.99 in R-Allowlist",
                "BT93O still needs BT93W.99=bt93o-precondition-green",
                "BT93P still needs BT93O.99 and BT93X.99",
                "BT94A still needs BT93P.4=BT94A-ready plus green gate",
            ],
        },
        "commands": {
            "write": "python python/scripts/bt93y_closure_gate.py --write-reports",
            "metaGate": "npm.cmd run gates:pre-commit",
            "build": "npm.cmd run build",
            "tests": "user-owned; not run by 93Y.99 unless explicitly requested",
        },
    }
    handover = {
        "schemaVersion": "bt93y-handover-package-v1",
        "ok": ok,
        "generatedAt": generated_at,
        "generatedBy": "python/scripts/bt93y_closure_gate.py",
        "git": git_info,
        "blockId": "BT93Y",
        "phaseId": "93Y.99",
        "resultClass": closure["resultClass"],
        "sourceClosureReport": {
            "path": _rel(CLOSURE_REPORT_PATH),
            "sha256AfterWrite": None,
        },
        "activeLineage": active_lineage,
        "replacementPolicy": closure["replacementPolicy"],
        "nextAllowedActions": REENTRY_ONLY_NEXT if ok else [],
        "blockedActions": list(BLOCKED_NEXT),
        "blockingStatus": blocking_status,
        "recommendations": recommendations,
        "nonGoalsPreserved": [
            "no BT93S/O/P/94A claim",
            "no candidate or freeze",
            "no holdout consumption",
            "no promote or rollout wording",
            "no PPO-Validate or BT95 handoff signal",
            "no productive runtime integration",
        ],
        "summary": closure["summary"],
    }
    handover["sourceClosureReport"]["sha256AfterWrite"] = _sha256_payload(closure)
    return closure, handover


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-reports", action="store_true")
    args = parser.parse_args()

    closure, handover = build_reports()
    if args.write_reports:
        _write_json(CLOSURE_REPORT_PATH, closure)
        _write_json(HANDOVER_PACKAGE_PATH, handover)
    print(
        json.dumps(
            {
                "ok": closure["ok"],
                "resultClass": closure["resultClass"],
                "bt93rReentryAllowed": closure["claimFlags"]["bt93rReentryAllowed"],
                "phaseCoverage": closure["phaseCoverage"],
                "dodCoverage": closure["dodCoverage"],
                "opensNext": closure["opensNext"],
                "blocksNext": closure["blocksNext"][:4],
                "outputs": closure["generatedArtifacts"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0 if closure["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
