export function createEntityRuntimeCompat(runtime) {
    return {
        _projectileSystem: runtime.systems.projectileSystem,
        _huntScoring: runtime.support.huntScoring,
        _eventBus: runtime.support.eventBus,
        _tmpVec: runtime.support.tempVectors.primary,
        _tmpVec2: runtime.support.tempVectors.secondary,
        _tmpDir: runtime.support.tempVectors.direction,
        _tmpDir2: runtime.support.tempVectors.alternateDirection,
        _tmpCamAnchor: runtime.support.tempVectors.cameraAnchor,
        _tmpCamRenderPos: runtime.support.tempVectors.cameraRenderPosition,
        _tmpCamRenderQuat: runtime.support.tempQuaternion,
        _tmpCollisionNormal: runtime.support.tempVectors.collisionNormal,
        _tmpPrevPlayerPosition: runtime.support.tempVectors.previousPlayerPosition,
        _fallbackArenaCollision: runtime.support.fallbackArenaCollision,
        _lockOnCache: runtime.support.lockOnCache,
        _trailSpatialIndex: runtime.support.trailSpatialIndex,
        _spawnPlacementSystem: runtime.support.spawnPlacementSystem,
        _collisionResponseSystem: runtime.support.collisionResponseSystem,
        _runtimeContext: runtime.context,
        _playerInputSystem: runtime.systems.playerInputSystem,
        _playerLifecycleSystem: runtime.systems.playerLifecycleSystem,
        _overheatGunSystem: runtime.systems.overheatGunSystem,
        _respawnSystem: runtime.systems.respawnSystem,
        _huntCombatSystem: runtime.systems.huntCombatSystem,
        _roundOutcomeSystem: runtime.systems.roundOutcomeSystem,
        _setupOps: runtime.systems.setupOps,
        _spawnOps: runtime.systems.spawnOps,
        _tickPipeline: runtime.systems.tickPipeline,
    };
}
